version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000" 