# Generated by Django 4.2.22 on 2025-12-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('base_forecast', models.FloatField()),
                ('base_urban', models.FloatField(blank=True, null=True)),
                ('base_rural', models.FloatField(blank=True, null=True)),
                ('adjusted_forecast', models.FloatField()),
                ('adjusted_urban', models.FloatField(blank=True, null=True)),
                ('adjusted_rural', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(default=0)),
                ('news_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FactorImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('canonical_weight', models.FloatField()),
                ('influence_probability', models.FloatField()),
                ('adjusted_weight', models.FloatField()),
                ('positive_prob', models.FloatField(default=0)),
                ('negative_prob', models.FloatField(default=0)),
                ('news_count', models.PositiveIntegerField(default=0)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='analyzer.dailymonitoring')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
