# Generated by Django 4.2.22 on 2026-04-08 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_dailymonitoring_id_alter_factorimpact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFactorSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_sentiment', models.FloatField(default=0)),
                ('delta_from_previous', models.FloatField(default=0)),
                ('total_news_count', models.PositiveIntegerField(default=0)),
                ('relevant_news_count', models.PositiveIntegerField(default=0)),
                ('positive_hits', models.PositiveIntegerField(default=0)),
                ('negative_hits', models.PositiveIntegerField(default=0)),
                ('neutral_hits', models.PositiveIntegerField(default=0)),
                ('max_positive_score', models.FloatField(default=0)),
                ('max_negative_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'factor__display_order'],
            },
        ),
        migrations.CreateModel(
            name='DailySentimentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('average_sentiment', models.FloatField(default=0)),
                ('delta_from_previous', models.FloatField(default=0)),
                ('risk_index', models.FloatField(default=0)),
                ('news_count', models.PositiveIntegerField(default=0)),
                ('factor_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('seed', 'Seed'), ('backfill', 'Backfill'), ('update', 'Update')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='success', max_length=20)),
                ('source', models.CharField(default='tass', max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('news_fetched', models.PositiveIntegerField(default=0)),
                ('news_stored', models.PositiveIntegerField(default=0)),
                ('classifications_created', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_probability', models.FloatField()),
                ('negative_probability', models.FloatField()),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=16)),
                ('confidence', models.FloatField(default=0)),
                ('is_relevant', models.BooleanField(default=False)),
                ('is_seed', models.BooleanField(default=False)),
                ('classified_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifications', to='analyzer.monitoringbatch')),
            ],
            options={
                'ordering': ['-news_item__published_at', 'factor__display_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='tass', max_length=64)),
                ('external_id', models.CharField(max_length=512)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('is_seed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('positive_label', models.CharField(max_length=255)),
                ('negative_label', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='factorimpact',
            name='monitoring',
        ),
        migrations.DeleteModel(
            name='DailyMonitoring',
        ),
        migrations.DeleteModel(
            name='FactorImpact',
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='analyzer.riskfactor'),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='analyzer.newsitem'),
        ),
        migrations.AddField(
            model_name='dailyfactorsentiment',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='analyzer.riskfactor'),
        ),
        migrations.AddField(
            model_name='dailyfactorsentiment',
            name='top_negative_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analyzer.newsitem'),
        ),
        migrations.AddField(
            model_name='dailyfactorsentiment',
            name='top_positive_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analyzer.newsitem'),
        ),
        migrations.AlterUniqueTogether(
            name='newsclassification',
            unique_together={('news_item', 'factor')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyfactorsentiment',
            unique_together={('factor', 'date')},
        ),
    ]
