# Generated by Django 4.2.22 on 2026-05-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_dailyfactorsentiment_dailysentimentsummary_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyfactorsentiment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='newsclassification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyfactorsentiment',
            name='engine',
            field=models.CharField(choices=[('bert', 'BERT'), ('llm', 'LLM')], default='bert', max_length=16),
        ),
        migrations.AddField(
            model_name='dailyfactorsentiment',
            name='factor_catalog_version',
            field=models.CharField(default='social-risk-factors-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='dailyfactorsentiment',
            name='model_name',
            field=models.CharField(default='cointegrated/rubert-base-cased-nli-threeway', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyfactorsentiment',
            name='prompt_version',
            field=models.CharField(default='bert-zero-shot-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='dailysentimentsummary',
            name='engine',
            field=models.CharField(choices=[('bert', 'BERT'), ('llm', 'LLM')], default='bert', max_length=16),
        ),
        migrations.AddField(
            model_name='dailysentimentsummary',
            name='factor_catalog_version',
            field=models.CharField(default='social-risk-factors-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='dailysentimentsummary',
            name='model_name',
            field=models.CharField(default='cointegrated/rubert-base-cased-nli-threeway', max_length=255),
        ),
        migrations.AddField(
            model_name='dailysentimentsummary',
            name='prompt_version',
            field=models.CharField(default='bert-zero-shot-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='monitoringbatch',
            name='engine',
            field=models.CharField(choices=[('bert', 'BERT'), ('llm', 'LLM')], default='bert', max_length=16),
        ),
        migrations.AddField(
            model_name='monitoringbatch',
            name='factor_catalog_version',
            field=models.CharField(default='social-risk-factors-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='monitoringbatch',
            name='model_name',
            field=models.CharField(default='cointegrated/rubert-base-cased-nli-threeway', max_length=255),
        ),
        migrations.AddField(
            model_name='monitoringbatch',
            name='prompt_version',
            field=models.CharField(default='bert-zero-shot-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='engine',
            field=models.CharField(choices=[('bert', 'BERT'), ('llm', 'LLM')], default='bert', max_length=16),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='evidence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='factor_catalog_version',
            field=models.CharField(default='social-risk-factors-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='model_name',
            field=models.CharField(default='cointegrated/rubert-base-cased-nli-threeway', max_length=255),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='pressure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='prompt_version',
            field=models.CharField(default='bert-zero-shot-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='relevance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysentimentsummary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monitoringbatch',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('partial_failed', 'Partial failed')], default='success', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dailyfactorsentiment',
            unique_together={('factor', 'date', 'engine', 'model_name', 'prompt_version', 'factor_catalog_version')},
        ),
        migrations.AlterUniqueTogether(
            name='dailysentimentsummary',
            unique_together={('date', 'engine', 'model_name', 'prompt_version', 'factor_catalog_version')},
        ),
        migrations.AlterUniqueTogether(
            name='newsclassification',
            unique_together={('news_item', 'factor', 'engine', 'model_name', 'prompt_version', 'factor_catalog_version')},
        ),
        migrations.CreateModel(
            name='MonitoringSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('engine', models.CharField(choices=[('bert', 'BERT'), ('llm', 'LLM')], default='llm', max_length=16)),
                ('model_name', models.CharField(max_length=255)),
                ('prompt_version', models.CharField(max_length=80)),
                ('factor_catalog_version', models.CharField(default='social-risk-factors-v1', max_length=80)),
                ('input_hash', models.CharField(max_length=64)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('worsening', 'Worsening'), ('stable', 'Stable'), ('mixed', 'Mixed')], default='stable', max_length=16)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16)),
                ('confidence', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('main_drivers', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_summaries', to='analyzer.riskfactor')),
            ],
            options={
                'ordering': ['-period_end', 'factor__display_order'],
                'unique_together': {('factor', 'period_start', 'period_end', 'engine', 'model_name', 'prompt_version', 'factor_catalog_version')},
            },
        ),
    ]
