# Generated by Django 4.2 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0004_alter_dailyfactorsentiment_unique_together_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="newsitem",
            index=models.Index(fields=["source", "-published_at"], name="news_item_source_date_idx"),
        ),
        migrations.AddIndex(
            model_name="newsitem",
            index=models.Index(fields=["is_seed", "-published_at"], name="news_item_seed_date_idx"),
        ),
        migrations.AddIndex(
            model_name="newsclassification",
            index=models.Index(fields=["engine", "factor", "is_relevant"], name="news_class_factor_idx"),
        ),
        migrations.AddIndex(
            model_name="newsclassification",
            index=models.Index(fields=["engine", "classified_at"], name="news_class_engine_time_idx"),
        ),
        migrations.AddIndex(
            model_name="dailysentimentsummary",
            index=models.Index(fields=["engine", "-date"], name="daily_summary_engine_date_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyfactorsentiment",
            index=models.Index(fields=["engine", "factor", "-date"], name="factor_sent_engine_date_idx"),
        ),
    ]
