# Generated by Django 4.2 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0005_monitoring_postgres_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyfactorsentiment",
            name="factor_catalog_version",
            field=models.CharField(default="social-risk-factors-v2", max_length=80),
        ),
        migrations.AlterField(
            model_name="dailysentimentsummary",
            name="factor_catalog_version",
            field=models.CharField(default="social-risk-factors-v2", max_length=80),
        ),
        migrations.AlterField(
            model_name="monitoringbatch",
            name="factor_catalog_version",
            field=models.CharField(default="social-risk-factors-v2", max_length=80),
        ),
        migrations.AlterField(
            model_name="monitoringsummary",
            name="factor_catalog_version",
            field=models.CharField(default="social-risk-factors-v2", max_length=80),
        ),
        migrations.AlterField(
            model_name="newsclassification",
            name="factor_catalog_version",
            field=models.CharField(default="social-risk-factors-v2", max_length=80),
        ),
    ]
